/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegulamentoRouteImport } from './routes/regulamento'
import { Route as PremiacaoRouteImport } from './routes/premiacao'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as PercursoRouteImport } from './routes/percurso'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitRouteImport } from './routes/kit'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FalhanopagamentoRouteImport } from './routes/falhanopagamento'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscricaoSucessoRouteImport } from './routes/inscricao.sucesso'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminPatrocinadoresRouteImport } from './routes/_authenticated/admin.patrocinadores'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminInscricoesRouteImport } from './routes/_authenticated/admin.inscricoes'
import { Route as AuthenticatedAdminGaleriaRouteImport } from './routes/_authenticated/admin.galeria'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminInscricoesIdRouteImport } from './routes/_authenticated/admin.inscricoes.$id'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoRoute = RegulamentoRouteImport.update({
  id: '/regulamento',
  path: '/regulamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiacaoRoute = PremiacaoRouteImport.update({
  id: '/premiacao',
  path: '/premiacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PercursoRoute = PercursoRouteImport.update({
  id: '/percurso',
  path: '/percurso',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FalhanopagamentoRoute = FalhanopagamentoRouteImport.update({
  id: '/falhanopagamento',
  path: '/falhanopagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoSucessoRoute = InscricaoSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => InscricaoRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPatrocinadoresRoute =
  AuthenticatedAdminPatrocinadoresRouteImport.update({
    id: '/patrocinadores',
    path: '/patrocinadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInscricoesRoute =
  AuthenticatedAdminInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGaleriaRoute =
  AuthenticatedAdminGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInscricoesIdRoute =
  AuthenticatedAdminInscricoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInscricoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/falhanopagamento': typeof FalhanopagamentoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRouteWithChildren
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/percurso': typeof PercursoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/premiacao': typeof PremiacaoRoute
  '/regulamento': typeof RegulamentoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/admin/inscricoes/$id': typeof AuthenticatedAdminInscricoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/falhanopagamento': typeof FalhanopagamentoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRouteWithChildren
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/percurso': typeof PercursoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/premiacao': typeof PremiacaoRoute
  '/regulamento': typeof RegulamentoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/admin/inscricoes/$id': typeof AuthenticatedAdminInscricoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/falhanopagamento': typeof FalhanopagamentoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRouteWithChildren
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/percurso': typeof PercursoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/premiacao': typeof PremiacaoRoute
  '/regulamento': typeof RegulamentoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/_authenticated/admin/inscricoes': typeof AuthenticatedAdminInscricoesRouteWithChildren
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/_authenticated/admin/inscricoes/$id': typeof AuthenticatedAdminInscricoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/falhanopagamento'
    | '/faq'
    | '/galeria'
    | '/inscricao'
    | '/kit'
    | '/login'
    | '/patrocinadores'
    | '/percurso'
    | '/politica-privacidade'
    | '/premiacao'
    | '/regulamento'
    | '/reset-password'
    | '/sucesso'
    | '/admin'
    | '/inscricao/sucesso'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/eventos'
    | '/admin/galeria'
    | '/admin/inscricoes'
    | '/admin/logs'
    | '/admin/pagamentos'
    | '/admin/patrocinadores'
    | '/admin/inscricoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/falhanopagamento'
    | '/faq'
    | '/galeria'
    | '/inscricao'
    | '/kit'
    | '/login'
    | '/patrocinadores'
    | '/percurso'
    | '/politica-privacidade'
    | '/premiacao'
    | '/regulamento'
    | '/reset-password'
    | '/sucesso'
    | '/admin'
    | '/inscricao/sucesso'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/eventos'
    | '/admin/galeria'
    | '/admin/inscricoes'
    | '/admin/logs'
    | '/admin/pagamentos'
    | '/admin/patrocinadores'
    | '/admin/inscricoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/falhanopagamento'
    | '/faq'
    | '/galeria'
    | '/inscricao'
    | '/kit'
    | '/login'
    | '/patrocinadores'
    | '/percurso'
    | '/politica-privacidade'
    | '/premiacao'
    | '/regulamento'
    | '/reset-password'
    | '/sucesso'
    | '/_authenticated/admin'
    | '/inscricao/sucesso'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/galeria'
    | '/_authenticated/admin/inscricoes'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/patrocinadores'
    | '/_authenticated/admin/inscricoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FalhanopagamentoRoute: typeof FalhanopagamentoRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  InscricaoRoute: typeof InscricaoRouteWithChildren
  KitRoute: typeof KitRoute
  LoginRoute: typeof LoginRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PercursoRoute: typeof PercursoRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PremiacaoRoute: typeof PremiacaoRoute
  RegulamentoRoute: typeof RegulamentoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento': {
      id: '/regulamento'
      path: '/regulamento'
      fullPath: '/regulamento'
      preLoaderRoute: typeof RegulamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premiacao': {
      id: '/premiacao'
      path: '/premiacao'
      fullPath: '/premiacao'
      preLoaderRoute: typeof PremiacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percurso': {
      id: '/percurso'
      path: '/percurso'
      fullPath: '/percurso'
      preLoaderRoute: typeof PercursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falhanopagamento': {
      id: '/falhanopagamento'
      path: '/falhanopagamento'
      fullPath: '/falhanopagamento'
      preLoaderRoute: typeof FalhanopagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/sucesso': {
      id: '/inscricao/sucesso'
      path: '/sucesso'
      fullPath: '/inscricao/sucesso'
      preLoaderRoute: typeof InscricaoSucessoRouteImport
      parentRoute: typeof InscricaoRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/patrocinadores': {
      id: '/_authenticated/admin/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/admin/patrocinadores'
      preLoaderRoute: typeof AuthenticatedAdminPatrocinadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inscricoes': {
      id: '/_authenticated/admin/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AuthenticatedAdminInscricoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galeria': {
      id: '/_authenticated/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inscricoes/$id': {
      id: '/_authenticated/admin/inscricoes/$id'
      path: '/$id'
      fullPath: '/admin/inscricoes/$id'
      preLoaderRoute: typeof AuthenticatedAdminInscricoesIdRouteImport
      parentRoute: typeof AuthenticatedAdminInscricoesRoute
    }
  }
}

interface AuthenticatedAdminInscricoesRouteChildren {
  AuthenticatedAdminInscricoesIdRoute: typeof AuthenticatedAdminInscricoesIdRoute
}

const AuthenticatedAdminInscricoesRouteChildren: AuthenticatedAdminInscricoesRouteChildren =
  {
    AuthenticatedAdminInscricoesIdRoute: AuthenticatedAdminInscricoesIdRoute,
  }

const AuthenticatedAdminInscricoesRouteWithChildren =
  AuthenticatedAdminInscricoesRoute._addFileChildren(
    AuthenticatedAdminInscricoesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminGaleriaRoute: typeof AuthenticatedAdminGaleriaRoute
  AuthenticatedAdminInscricoesRoute: typeof AuthenticatedAdminInscricoesRouteWithChildren
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminPatrocinadoresRoute: typeof AuthenticatedAdminPatrocinadoresRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminGaleriaRoute: AuthenticatedAdminGaleriaRoute,
  AuthenticatedAdminInscricoesRoute:
    AuthenticatedAdminInscricoesRouteWithChildren,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminPatrocinadoresRoute: AuthenticatedAdminPatrocinadoresRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface InscricaoRouteChildren {
  InscricaoSucessoRoute: typeof InscricaoSucessoRoute
}

const InscricaoRouteChildren: InscricaoRouteChildren = {
  InscricaoSucessoRoute: InscricaoSucessoRoute,
}

const InscricaoRouteWithChildren = InscricaoRoute._addFileChildren(
  InscricaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FalhanopagamentoRoute: FalhanopagamentoRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  InscricaoRoute: InscricaoRouteWithChildren,
  KitRoute: KitRoute,
  LoginRoute: LoginRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PercursoRoute: PercursoRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PremiacaoRoute: PremiacaoRoute,
  RegulamentoRoute: RegulamentoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
